### ISSUE TITLE
Cannot reproduce the result in "Scene detection demo.ipynb".

### ISSUE THREAD

**Issue by xiaozhi2015** [TristanGomez44/sceneDetection#1]
@TristanGomez44 
Here is my result of "sintel-1024-surround.mp4":
![image](https://user-images.githubusercontent.com/12682406/77845574-866c1800-71e2-11ea-88b5-2715f4895ee9.png)

**Comment by xiaozhi2015** [comment]
@TristanGomez44 
Should I preprocess the "sintel-1024-surround.mp4" file ?

**Comment by TristanGomez44** [comment]
Hi xiaozhi2015 ! I am sorry for not answering you but I did this work during my internship and I don't have acess to the files I had at that time.
However I have asked my former supervisor for help and I have been able to reproduce what you have obtained. I will investigate this during the next few days.

**Comment by xiaozhi2015** [comment]
Much thx! I have reproduced the result in "trainVal.py" with eval mode.
BTY, I didn't find your article, can you tell me the title of it?

**Comment by TristanGomez44** [comment]
The paper isn't published, I will send you the arxiv version in the next few days !
Glad you were able to reproduce results.

**Comment by xiaozhi2015** [comment]
OK. Look forward to ...

**Comment by TristanGomez44** [comment]
Hi ! Here's the link https://drive.google.com/file/d/1P08NrvqOp7yEv2DHwszSFCOSaz2atRq8/view?usp=sharing I haven't uploaded it on Arxiv yet !

**Comment by xiaozhi2015** [comment]
Great work. Hope it be delivered at the top conference.

**Comment by TristanGomez44** [comment]
Thank you a lot ! :)
